services:
  otel_collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel_collector
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./collector.yml:/etc/otel-collector-config.yml
      - ./data:/var/lib/otel-data
    command:
      "--config=/etc/otel-collector-config.yml"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_ENDPOINT:http://otel_collector:4317}
    labels:
      org.label-schema.group: "monitoring"