services:
  otel_collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./collector.yml:/etc/otel/config.yaml
      - ./data:/var/lib/otel-data
    command:
      "--config=/etc/otel/config.yml"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    labels:
      org.label-schema.group: "monitoring"