services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    user: "0:0"
    volumes:
      - ./loki-config.yaml:/etc/loki-config.yaml:ro
      - ./loki-data:/loki
    ports:
      - "3100:3100"  # Loki HTTP API
    command: ["-config.file=/etc/loki-config.yaml"]