services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    user: "0:0"
    volumes:
      - ./loki.yml:/etc/loki-config.yml:ro
      - ./data:/loki
    command: ["-config.file=/etc/loki-config.yml"]
    labels:
      org.label-schema.group: "monitoring"