services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    user: "0:0"
    volumes:
      - ./loki.yaml:/etc/loki-config.yaml:ro
      - ./data:/loki
    command: ["-config.file=/etc/loki-config.yaml"]
    labels:
      org.label-schema.group: "monitoring"