networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1

services:
  pushgateway:
    extends:
      file: ./pushgateway/compose.yml
      service: pushgateway
      ports:
        - "9091:9091"
      networks:
        monitoring:
          ipv4_address: "10.10.0.2"

  prometheus:
    extends:
      file: prometheus/compose.yml
      service: prometheus
      ports:
        - "9090:9090"
      depends_on:
        - pushgateway
      networks:
        monitoring:
          ipv4_address: "10.10.0.3"
  alertmanager:
    extends:
      file: ./alertmanager/compose.yml
      service: alertmanager
      ports:
        - "9093:9093"
      networks:
        monitoring:
          ipv4_address: "10.10.0.4"
  otel_collector:
    extends:
      file: otel_collector/compose.yml
      service: otel_collector
      ports:
      - "4318:4318"   # OTLP HTTP
#      - "1888:1888"   # pprof extension
#      - "8888:8888"   # Prometheus metrics exposed by the collector
#      - "8889:8889"   # Prometheus exporter metrics
#      - "13133:13133" # health_check extension
#      - "4317:4317"   # OTLP gRPC receiver
#      - "55679:55679" # zpages extension
      depends_on:
        - prometheus
      networks:
        monitoring:
          ipv4_address: "10.10.0.5"
  loki:
    extends:
      file: loki/compose.yml
      service: loki
      ports:
        - "3100:3100"  # Loki HTTP API
      networks:
        monitoring:
          ipv4_address: "10.10.0.6"

  tempo:
    extends:
      file: tempo/compose.yml
      service: tempo
      ports:
        - "3200:3200"
      depends_on:
        - otel_collector
        - loki
      networks:
        monitoring:
          ipv4_address: "10.10.0.7"

  mimir:
    extends:
      file: mimir/compose.yml
      service: mimir
      ports:
        - "7200:7200"  # Mimir HTTP API
      networks:
        monitoring:
          ipv4_address: "10.10.0.8"

  grafana:
    extends:
      file: grafana/compose.yml
      service: grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      networks:
        monitoring:
          ipv4_address: "10.10.0.9"
