services:
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    restart: always
    volumes:
      - ./mimir-config.yaml:/etc/mimir-config.yaml:ro
      - ./mimir-data:/mimir
    ports:
      - "7200:7200"  # Mimir HTTP API
    command: ["-config.file=/etc/mimir-config.yaml"]