services:
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./mimir.yml:/etc/mimir-config.yml:ro
      - ./data:/mimir
    command: ["-config.file=/etc/mimir-config.yml"]
    labels:
      org.label-schema.group: "monitoring"