services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_FEATURE_TOGGLES_TRACE_SERVICE_GRAPH=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=${GF_BASE_URL}
    volumes:
      - ./data:/var/lib/grafana:rw  # Persistent storage for Grafana data
      - ./config:/etc/grafana:ro    # Persistent storage for Grafana configuration
    labels:
      org.label-schema.group: "monitoring"

