services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: unless-stopped
    user: "0:0"
    command:
      - "-config.file=/etc/tempo.yml"
    volumes:
      - ./tempo.yml:/etc/tempo.yml
      - ./data:/var/lib/tempo
    labels:
      org.label-schema.group: "monitoring"
